=== dosseh/Dataviz_Arbres-hi-rarchies-et-recursion/Exercice5_2/data/Dossier_a_explorer/XML/payslangue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- paysLangue -->
<!-- -pays ne contient que des clé etrangères et aucun autre éléments en particulier, du coup on le renseigne comme etant EMPY -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://ust-infoserv.univlehavre.lan/~mf120453/" elementFormDefault="qualified">
    <xs:element name="payslangue">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="payslangue_obj">
                    <xs:attribute name="pays_id" use="required" type="xs:IDREF"/>
                    <xs:attribute name="orga_id" use="required" type="xs:IDREF"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="payslangue_obj">
        <xs:sequence>
            <xs:element ref="payslangue_obj"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="payslangue_obj">
        <xs:complexType/>
    </xs:element>
</xs:schema>

=== dosseh/Dataviz_Arbres-hi-rarchies-et-recursion/Exercice5_2/data/Dossier_a_explorer/XML/payslangue.xml
<?xml version = "1.0" encoding="UTF-8" ?>
<payslangue xmlns="http://ust-infoserv.univlehavre.lan/~mf120453/XML">
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://ust-infoserv.univlehavre.lan/~mf120453/XML/ payslangue.xsd">
    <payslangue_obj pays_id="france" langue_id="francais"/>
    <payslangue_obj pays_id="allemagne" langue_id="allemand"/>
    <payslangue_obj pays_id="ITALIE" langue_id="italien"/>
    <payslangue_obj pays_id="Espagne" langue_id="espagnol"/>
    <payslangue_obj pays_id="RU" langue_id="anglais"/>
    <payslangue_obj pays_id="Suisse" langue_id="allemand"/>
    <payslangue_obj pays_id="Suisse" langue_id="romanche"/>
    <payslangue_obj pays_id="Suisse" langue_id="francais"/>
    <payslangue_obj pays_id="Islande" langue_id="islandais"/>
    <payslangue_obj pays_id="Norvege" langue_id="norvegiens"/>
    <payslangue_obj pays_id="Portugal" langue_id="portugais"/>
    <payslangue_obj pays_id="Portugal" langue_id="mirandais"/>
    <payslangue_obj pays_id="Suede" langue_id="suedois"/>
    <payslangue_obj pays_id="Finlande" langue_id="finnois"/>
    <payslangue_obj pays_id="Finlande" langue_id="suedois"/>
    <payslangue_obj pays_id="Belgique" langue_id="francais"/>
    <payslangue_obj pays_id="Belgique" langue_id="allemand"/>
    <payslangue_obj pays_id="Belgique" langue_id="neerlandais"/>
    <payslangue_obj pays_id="grece" langue_id="grec"/>
    
</payslangue>
